## Standard Jeyll config options
permalink: /:year/:month/:day/:title.html
exclude: [ _posts/source/, _posts/_private/, assets/figures]
lunr_excludes: [atom.xml, 404.html, search.html, categories.md, tags.md, calendar.md]

## Toggles to activate/deactivate various plugins
## Deactivate these for faster site generation, or in creating archival versions ##

#redirects: yes ## A flag to turn on the redirects plugin
#searchindex: yes ## A flag to turn on the search index plugin.
#pageviews: yes ## toggle on sidebar pageviews
#lunrsearch: no ## Javascript will still be included, but Jekyll won't build the database



## Useful metadata, available to a liquid filter as site.title, site.author.name, etc
## Used in _includes templates headers and footers.
title: intro2r
tagline: It's not as bad as you think
author:
  name: Simon Queenborough
  givenName: Simon
  familyName: Queenborough
  twitter: saqueenborough
  github: saq
url: http://www.intro2r.info
repo: https://github.com/intro2r/intro2r.github.io # used in linking history

## Google Analytics key (in _includes/analytics.html)
#analytics: 


## Markdown Parser (standard Jekyll argument, extended to special parser)
markdown: kramdown
#pandoc:
#  extensions:
#    - smart
#    - mathjax
# - template: 'assets/datauri_template.html' # Use with 'self-contained' to avoid header text in body
# - self-contained # Archive images in posts as URIs. Very slow, for archiving only.
# - mathml # Use mathml for equations (Archival, HTML5/XML valid syntax)


